Feature/production setup
ccims/gropius pull request #5
Opened 2022-09-21 09:28 UTC by nk-coding

# TODO
- login service in production docker-compose

2022-09-21 16:56 UTC, chriku requested changes

2022-09-21 16:56 UTC, chriku commented on docker-compose.yml
> +      - GROPIUS_SYNC_GITHUB_LOGIN_SERVICE_BASE=http://loginservice:3000/
```suggestion
      - GROPIUS_SYNC_LOGIN_SERVICE_BASE=http://loginservice:3000/
```

2022-09-21 16:56 UTC, chriku commented on docker-compose.yml
> +      - GROPIUS_SYNC_GITHUB_API_SECRET=TODO_loginSecret
```suggestion
      - GROPIUS_SYNC_API_SECRET=TODO_loginSecret
```

2022-10-01 14:45 UTC, nk-coding commented
Temporarily removed dependency of github sync on loginservice until @ModellbahnFreak adds his setup

2022-10-08 17:33 UTC, chriku approved these changes

2022-10-14 23:25 UTC, merged